[tool.poetry]
name = "ragas-cicd"
version = "0.1.0"
description = ""
authors = ["Asahi Kuroki <kurok011@umn.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
